name: chartmogul
description: A high-level ChartMogul API Dart Client
author: Benjamin Barbersmith <ben@barbersmith.com>
homepage: https://www.github.com/benbarbersmith/chartmogul-dart
repository: https://www.github.com/benbarbersmith/chartmogul-dart
version: 0.0.5

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  http: "^0.12.0"
dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.2.3
  meta: ^1.1.0
  mockito: ^4.0.0
  pedantic: "^1.8.0+1"
  test: "^1.5.1"
